<package>
    <description brief="Model autogenerated in ESROCOS">
        This package ${component_name}
    </description>
    <author>GMV Aerospace & Defence S.A.U.</author>
    <copyright>GMV 2018</copyright>
    <license>GPLv2</license>
    %for d in dependencies:
    <depend package="${d}"/>
    %endfor
</package>
