
/* Header file for function hello_world in C language
 * Generated by TASTE on 2022-12-06 11:59:37
 * Context Parameters present : NO
 * Provided interfaces : step
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ TASTE::Is_Component_Type = false
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void hello_world_startup(void);

/* Provided interfaces */
void hello_world_PI_step( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
