
/* Header file for function hello_world in C language
 * Generated by TASTE on 2021-06-01 18:48:46
 * Context Parameters present : NO
 * Provided interfaces : step
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 97729 79852 129908 105833
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void hello_world_startup(void);

/* Provided interfaces */
void hello_world_PI_step( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
