/* Body file for function hello_world
 * Generated by TASTE on 2021-06-01 11:16:56
 * You can edit this file, it will not be overwritten
 * Provided interfaces : step
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 97729 79852 147308 109170
 * Timers              : 
 */

#include "hello_world.h"
//#include <stdio.h>

asn1SccT_UInt64 number;

void hello_world_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[hello_world] Startup");
}

void hello_world_PI_step(void)
{
   // Write your code here
   number++;
   puts("[Hello_world] Time from you start the application");
   PrintT_UInt64("Seconds", &number);
}


